import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowLeft, MapPin, CreditCard, Loader2, Copy, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Separator } from '@/components/ui/separator';
import { BuyerLayout } from '@/components/buyer/BuyerLayout';
import { useCart } from '@/contexts/CartContext';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { useQuery } from '@tanstack/react-query';
import { toast } from '@/hooks/use-toast';

const checkoutSchema = z.object({
  recipient_name: z.string().min(2, 'Nama penerima minimal 2 karakter'),
  phone: z.string().min(10, 'Nomor telepon tidak valid').max(15),
  domicile_id: z.string().min(1, 'Pilih domisili'),
  address: z.string().min(10, 'Alamat minimal 10 karakter'),
  landmark: z.string().optional(),
  notes: z.string().optional(),
});

type CheckoutForm = z.infer<typeof checkoutSchema>;

export default function Checkout() {
  const navigate = useNavigate();
  const { items, subtotal, clearCart } = useCart();
  const { user, profileId } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [orderCreated, setOrderCreated] = useState<{ orderNumber: string; total: number } | null>(null);
  const [copied, setCopied] = useState(false);

  const { data: domiciles } = useQuery({
    queryKey: ['domiciles'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('domiciles')
        .select('id, name, city')
        .eq('is_active', true)
        .order('name');
      if (error) throw error;
      return data;
    },
  });

  const { data: buyerProfile } = useQuery({
    queryKey: ['buyer-profile', user?.id],
    queryFn: async () => {
      if (!user?.id) return null;
      const { data, error } = await supabase
        .from('buyer_profiles')
        .select('*')
        .eq('user_id', user.id)
        .maybeSingle();
      if (error) throw error;
      return data;
    },
    enabled: !!user?.id,
  });

  const form = useForm<CheckoutForm>({
    resolver: zodResolver(checkoutSchema),
    defaultValues: {
      recipient_name: buyerProfile?.full_name || '',
      phone: buyerProfile?.phone || '',
      domicile_id: buyerProfile?.domicile_id || '',
      address: '',
      landmark: '',
      notes: '',
    },
  });

  const adminFee = 2000;
  const shippingCost = 5000;
  const total = subtotal + adminFee + shippingCost;

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0,
    }).format(price);
  };

  const onSubmit = async (formData: CheckoutForm) => {
    if (!profileId || items.length === 0) {
      toast({
        title: 'Error',
        description: 'Keranjang kosong atau Anda belum login',
        variant: 'destructive',
      });
      return;
    }

    setIsSubmitting(true);
    try {
      // Create order - order_number is generated by trigger
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          buyer_id: profileId,
          order_number: '', // Will be overwritten by trigger
          subtotal,
          admin_fee: adminFee,
          shipping_cost: shippingCost,
          total,
          notes: formData.notes || null,
        } as any)
        .select('id, order_number')
        .single();

      if (orderError) throw orderError;

      // Create order address
      const { error: addressError } = await supabase
        .from('order_addresses')
        .insert({
          order_id: order.id,
          recipient_name: formData.recipient_name,
          phone: formData.phone,
          domicile_id: formData.domicile_id,
          address: formData.address,
          landmark: formData.landmark || null,
          notes: formData.notes || null,
        });

      if (addressError) throw addressError;

      // Create order items
      const orderItems = items.map((item) => ({
        order_id: order.id,
        product_id: item.productId,
        product_name: item.name,
        quantity: item.quantity,
        price_at_order: item.price,
        subtotal: item.price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      setOrderCreated({ orderNumber: order.order_number, total });
      clearCart();

      toast({
        title: 'Pesanan Berhasil Dibuat!',
        description: `Nomor pesanan: ${order.order_number}`,
      });
    } catch (error: any) {
      console.error('Checkout error:', error);
      toast({
        title: 'Gagal membuat pesanan',
        description: error.message || 'Terjadi kesalahan',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (orderCreated) {
    return (
      <BuyerLayout>
        <div className="max-w-md mx-auto py-8">
          <Card>
            <CardHeader className="text-center">
              <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
                <Check className="w-8 h-8 text-primary" />
              </div>
              <CardTitle>Pesanan Berhasil!</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="text-center">
                <p className="text-muted-foreground mb-2">Nomor Pesanan</p>
                <div className="flex items-center justify-center gap-2">
                  <span className="font-mono font-bold text-lg">{orderCreated.orderNumber}</span>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8"
                    onClick={() => copyToClipboard(orderCreated.orderNumber)}
                  >
                    {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  </Button>
                </div>
              </div>

              <Separator />

              <div>
                <p className="text-muted-foreground mb-2 text-center">Total Pembayaran</p>
                <p className="text-2xl font-bold text-primary text-center">
                  {formatPrice(orderCreated.total)}
                </p>
              </div>

              <Card className="bg-muted/50">
                <CardContent className="p-4">
                  <h4 className="font-semibold mb-2">Transfer ke:</h4>
                  <div className="space-y-1 text-sm">
                    <p><span className="text-muted-foreground">Bank:</span> BCA</p>
                    <p><span className="text-muted-foreground">No. Rekening:</span> 1234567890</p>
                    <p><span className="text-muted-foreground">Atas Nama:</span> Osher Shop</p>
                  </div>
                </CardContent>
              </Card>

              <p className="text-sm text-muted-foreground text-center">
                Setelah transfer, konfirmasi pembayaran melalui halaman pesanan Anda.
              </p>

              <div className="flex gap-3">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={() => navigate('/buyer/catalog')}
                >
                  Belanja Lagi
                </Button>
                <Button
                  className="flex-1"
                  onClick={() => navigate('/buyer/orders')}
                >
                  Lihat Pesanan
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </BuyerLayout>
    );
  }

  if (items.length === 0) {
    navigate('/buyer/cart');
    return null;
  }

  return (
    <BuyerLayout>
      <div className="max-w-2xl mx-auto">
        <Button
          variant="ghost"
          className="mb-4 gap-2"
          onClick={() => navigate('/buyer/cart')}
        >
          <ArrowLeft className="w-4 h-4" />
          Kembali ke Keranjang
        </Button>

        <h1 className="text-xl font-bold text-foreground mb-4">Checkout</h1>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            {/* Delivery Address */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <MapPin className="w-4 h-4" />
                  Alamat Pengiriman
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <FormField
                  control={form.control}
                  name="recipient_name"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Nama Penerima</FormLabel>
                      <FormControl>
                        <Input placeholder="Nama lengkap penerima" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="phone"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>No. Telepon</FormLabel>
                      <FormControl>
                        <Input placeholder="08xxxxxxxxxx" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="domicile_id"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Domisili</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Pilih domisili" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {domiciles?.map((dom) => (
                            <SelectItem key={dom.id} value={dom.id}>
                              {dom.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="address"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Alamat Lengkap</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Nama jalan, nomor rumah, RT/RW, kelurahan, kecamatan"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="landmark"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Patokan (Opsional)</FormLabel>
                      <FormControl>
                        <Input placeholder="Dekat masjid, sebelah toko..." {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="notes"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Catatan (Opsional)</FormLabel>
                      <FormControl>
                        <Textarea placeholder="Catatan untuk kurir..." {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Order Summary */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <CreditCard className="w-4 h-4" />
                  Ringkasan Pesanan
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="space-y-2">
                  {items.map((item) => (
                    <div key={item.productId} className="flex justify-between text-sm">
                      <span className="text-muted-foreground">
                        {item.name} x{item.quantity}
                      </span>
                      <span>{formatPrice(item.price * item.quantity)}</span>
                    </div>
                  ))}
                </div>
                <Separator />
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span>{formatPrice(subtotal)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Biaya Admin</span>
                  <span>{formatPrice(adminFee)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Ongkos Kirim</span>
                  <span>{formatPrice(shippingCost)}</span>
                </div>
                <Separator />
                <div className="flex justify-between font-bold">
                  <span>Total</span>
                  <span className="text-primary">{formatPrice(total)}</span>
                </div>
              </CardContent>
            </Card>

            <Button type="submit" className="w-full" size="lg" disabled={isSubmitting}>
              {isSubmitting ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Memproses...
                </>
              ) : (
                `Buat Pesanan - ${formatPrice(total)}`
              )}
            </Button>
          </form>
        </Form>
      </div>
    </BuyerLayout>
  );
}
